# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d98085edb61cdf7ee0ce2b26efb45bac"
name = "pool-dropship"
handle = "pool-dropship"
application_url = "https://expanding-israeli-sherman-colors.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aquax-doc.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locations,read_orders,read_products,read_script_tags,write_customers,write_inventory,write_locations,write_orders,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://expanding-israeli-sherman-colors.trycloudflare.com/auth/callback",
  "https://expanding-israeli-sherman-colors.trycloudflare.com/auth/shopify/callback",
  "https://expanding-israeli-sherman-colors.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
